web:
  # Flask (web) configuration
  ip: "0.0.0.0"
  port: 80

database:
  # RethinkDB configuration
  ip: "127.0.0.1"
  port: 28015
  database_name: "battle_myth_theater"

admin:
  username: "admin"                        #Insecure, change from example credentials.
  password: "admin"                        #Insecure, change from example credentials.

game:
  max_stat_points: 20

debug: true
