image: python:3.6.5-stretch

services:
  - rethinkdb:2.3.6

variables:
  RETHINKDB_HOST: "rethinkdb"

stages:
  - test

test:
  tags:
  - docker

  stage: test

  script:

    # Install python dependencies
    - apt-get update
    - apt-get -y install build-essential libffi-dev python-dev
    - pip install pipenv
    - pipenv sync --dev

    # Test
    - pipenv run test

    # Lint
    - pipenv run flake8
