image: python:3.6.5-stretch

stages:
  - test

test:
  tags:
  - docker

  stage: test

  script:
    # Install dependencies
    - apt-get update
    - apt-get install build-essential libffi-dev python-dev
    - pip install pipenv
    - pipenv sync --dev

    # Lint
    - pipenv run flake8
