# This file is used by GitLab to tell it how to build and test your code.
# You probably don't need to modify this - please don't touch it unless you're absolutely sure you need to.

image: pythondiscord/site-ci:latest

stages:
  - test

test:
  tags:
  - docker

  stage: test

  script:
    # Install dependencies
    - pip install pipenv
    - pipenv sync --dev

    # Lint
    - pipenv run flake8
