connection details:
    ip: 0.0.0.0
    port: 80
admin details:
    admin username: admin                #Insecure, change from example credentials.
    admin password: admin                #Insecure, change from example credentials.
user details:
    allow multiple accounts from ip: yes #Allow multiple registrations from a single IP?
