connection:
    ip: 0.0.0.0
    port: 80
admin:
    username: admin                      #Insecure, change from example credentials.
    password: admin                      #Insecure, change from example credentials.
user:
    allow_multiple_accounts_from_ip: yes #Allow multiple registrations from a single IP?
